version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d